"""add file_previews table

Revision ID: 13d393133c33
Revises: f34cad5b261b
Create Date: 2026-03-17 16:00:44.500887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d393133c33'
down_revision: Union[str, Sequence[str], None] = 'f34cad5b261b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_previews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('preview_type', sa.String(), nullable=False),
    sa.Column('preview_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_previews')
    # ### end Alembic commands ###
