"""add notes and file tags

Revision ID: 4eb43862f85f
Revises: 55b24ab29456
Create Date: 2026-04-04 12:22:28.131911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb43862f85f'
down_revision: Union[str, Sequence[str], None] = '55b24ab29456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'notes')
    op.drop_column('datasets', 'notes')
    # ### end Alembic commands ###
