"""add unique constraint for file previews

Revision ID: 55b24ab29456
Revises: baf5b74b7185
Create Date: 2026-03-18 21:20:13.001998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b24ab29456'
down_revision: Union[str, Sequence[str], None] = '13d393133c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_file_preview_type', 'file_previews', ['file_id', 'preview_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_file_preview_type', 'file_previews', type_='unique')
    # ### end Alembic commands ###
