"""add structured file metadata

Revision ID: 6251e34f1f43
Revises: d373b144b21b
Create Date: 2026-04-10 07:32:35.584109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6251e34f1f43'
down_revision: Union[str, Sequence[str], None] = 'd373b144b21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('measurement_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('files', sa.Column('excitation_power', sa.Float(), nullable=True))
    op.add_column('files', sa.Column('objective', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'objective')
    op.drop_column('files', 'excitation_power')
    op.drop_column('files', 'measurement_date')
    # ### end Alembic commands ###
