"""rename file_name to filename

Revision ID: f34cad5b261b
Revises: 3117a2319bc3
Create Date: 2026-03-14 21:55:51.769694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34cad5b261b'
down_revision: Union[str, Sequence[str], None] = '3117a2319bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "file_name", new_column_name="filename")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "filename", new_column_name="file_name")
    # ### end Alembic commands ###
